import 'package:isar_community/isar.dart';
import 'package:uuid/uuid.dart';

part 'm_reminder.g.dart';

// Reminder model class
@collection
class Reminder {
  // Auto-increment ID generated by Isar
  Id id = Isar.autoIncrement;

  @Index(unique: true)
  late String uid;

  String title;
  String content;
  String noteUID;
  DateTime? scheduledDT;
  bool isActive;
  bool isPinned;

  Reminder({
    String uid = '',
    required this.title,
    required this.content,
    required this.noteUID,
    this.isActive = false,
    this.isPinned = false,
    this.scheduledDT,
  }) : uid = uid.isEmpty ? const Uuid().v4() : uid;

  // Convert Reminder object to a Map for Firestore
  Map<String, dynamic> toMap(String userId) {
    return {
      'userId': userId, // Essential for fetching
      'title': title,
      'content': content,
      'noteUID': noteUID,
      'scheduledDT': scheduledDT?.toIso8601String(),
      'isActive': isActive,
      'isPinned': isPinned,
      'uid': uid,
    };
  }

  // Create a Reminder object from Firestore data
  factory Reminder.fromMap(Map<String, dynamic> map) {
    DateTime? scheduledDate;

    final scheduledValue = map['scheduledDT'];
    if (scheduledValue is String && scheduledValue.isNotEmpty) {
      scheduledDate = DateTime.tryParse(scheduledValue);
    }

    return Reminder(
      uid: map['uid'],
      title: map['title'] as String? ?? '',
      content: map['content'] as String? ?? '',
      noteUID: map['noteUID'] as String? ?? '',
      scheduledDT: scheduledDate,
      isActive: map['isActive'] as bool? ?? false,
      isPinned: map['isPinned'] as bool? ?? false,
    );
  }

  /// Copy with updated values
  Reminder copyWith({
    Id? id,
    String? uid,
    String? title,
    String? content,
    String? noteUID,
    DateTime? scheduledDT,
    bool? isActive,
    bool? isPinned,
  }) {
    final reminder = Reminder(
      uid: uid ?? this.uid,
      title: title ?? this.title,
      content: content ?? this.content,
      noteUID: noteUID ?? this.noteUID,
      scheduledDT: scheduledDT ?? this.scheduledDT,
      isActive: isActive ?? this.isActive,
      isPinned: isPinned ?? this.isPinned,
    );

    reminder.id = id ?? this.id;
    return reminder;
  }
}
