import 'dart:ui';

import 'package:isar_community/isar.dart';
import 'package:uuid/uuid.dart';

part 'm_group.g.dart';

// Group model class
@collection
class Group {
  // Auto-increment ID generated by Isar
  // Unique group ID (Firebase ID or UUID)
  Id id = Isar.autoIncrement;

  @Index(unique: true)
  late String uid;

  String gName; // Group name (e.g., Work, Personal)
  String? description; // Optional description
  DateTime createdAt;
  DateTime updatedAt;
  String decorColor; 
  int noteCount; // Count for quick display
  List<String>? notesUidsList; // uids of notes inside group

  Group({
    String uid = '',
    required this.gName,
    this.description,
    required this.createdAt,
    required this.updatedAt,
    required this.decorColor,
    this.noteCount = 0,
    this.notesUidsList,
  }) : uid = uid.isEmpty ? const Uuid().v4() : uid;
  // uid is added beacause when groups are fetched from firebase they get new isar id, because of which duplicate groups/folders are added in firebase.
  // First - Exist in isar
  // Second - From firebase
  // Both have same data.

  //  Automatically converts the string to a Flutter Color object
  @ignore
  Color get color => Color(int.parse("0x$decorColor"));

  // Convert Group object to a Map for Firestore
  Map<String, dynamic> toMap(String userId) {
    return {
      'userId': userId, // Essential for fetching
      'gName': gName,
      'description': description,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
      'decorColor': decorColor,
      'noteCount': noteCount,
      'notesUidsList': notesUidsList,
      // list of note uids
      // Firebase supports arrays of integers directly
      'uid': uid,
    };
  }

  // Create a Group object from Firestore data
  factory Group.fromMap(Map<String, dynamic> map) {
    return Group(
      gName: map['gName'] ?? '',
      description: map['description'] ?? '',
      createdAt: map['createdAt'] != null
          ? DateTime.parse(map['createdAt'])
          : DateTime.now(),
      updatedAt: map['updatedAt'] != null
          ? DateTime.parse(map['updatedAt'])
          : DateTime.now(),
      decorColor: map['decorColor'],
      noteCount: map['noteCount'] ?? 0,
      // Safely convert dynamic list to List<int>
      notesUidsList: map['notesUidsList'] != null
          ? List<String>.from(map['notesUidsList'])
          : [],
      uid: map['uid'],
    );
  }
}
