import 'dart:ui';

import 'package:isar_community/isar.dart';
import 'package:uuid/uuid.dart';

part 'm_note.g.dart';
// dart run build_runner build -> Command to generate above file

// Note model class
@collection
class Note {
  // Auto-increment ID generated by Isar
  // For local DBs like Isar/Hive. Optional for Firebase.
  Id id = Isar.autoIncrement;

  @Index(unique: true)
  late String uid;

  String title;
  String content;
  DateTime createdAt;
  DateTime updatedAt;
  String decorColor; // Optional: for UI customization (hex value)

  // Differentiating Notes and CheckList
  bool isCheckList;

  // Differentiating Notes and Calender Notes
  bool calNote;
  DateTime? selectedD;

  // Differentiating grouped and ungrouped notes
  bool grouped;

  // Differentiating Notes and Protected Notes
  bool isProtected;

  Note({
    String uid = '',
    required this.title,
    required this.content,
    required this.createdAt,
    required this.updatedAt,
    required this.decorColor,
    this.isCheckList = false,
    this.calNote = false,
    this.isProtected = false,
    this.selectedD, // default null
    this.grouped = false,
  }) : uid = uid.isEmpty
           ? const Uuid().v4()
           : uid; // Automatically creates a uid.
  // uid is added because it is unique id that is created first time and stored in the object.
  // note uid helps in grouping, group object stores a list of note uids
  // It stays same in isar as well as firebase. It never changes.

  //  Automatically converts the string to a Flutter Color object
  @ignore
  Color get color => Color(int.parse("0x$decorColor"));

  // Convert Group object to a Map for Firestore
  Map<String, dynamic> toMap(String userId) {
    return {
      'userId': userId, // Essential for fetching
      'title': title,
      'content': content,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
      'decorColor': decorColor,
      'calNote': calNote,
      'selectedD': selectedD?.toIso8601String(),
      'grouped': grouped,
      'uid': uid,
      'isProtected': isProtected,
      'isCheckList': isCheckList,
    };
  }

  // Create a Group object from Firestore data
  factory Note.fromMap(Map<String, dynamic> map) {
    return Note(
      title: map['title'] ?? '',
      content: map['content'] ?? '',
      createdAt: map['createdAt'] != null
          ? DateTime.parse(map['createdAt'])
          : DateTime.now(),
      updatedAt: map['updatedAt'] != null
          ? DateTime.parse(map['updatedAt'])
          : DateTime.now(),
      decorColor: map['decorColor'],
      calNote: map['calNote'],
      isProtected: map['isProtected'],
      isCheckList: map['isCheckList'],
      selectedD: map['selectedD'] != null
          ? DateTime.parse(map['selectedD'])
          : null,
      grouped: map['grouped'],
      uid: map['uid'],
    );
  }
}
