// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlwjeEjhBgs74inmVr9Ly50cZuZMlLRW0',
    appId: '1:253672631306:web:9dde54d843fd5a32c583f3',
    messagingSenderId: '253672631306',
    projectId: 'tasknote-e60f0',
    authDomain: 'tasknote-e60f0.firebaseapp.com',
    storageBucket: 'tasknote-e60f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYhchX-nX21Lm8eoqE8EI0dFvRjdDvqSU',
    appId: '1:253672631306:android:fdaa2252afc7f1e7c583f3',
    messagingSenderId: '253672631306',
    projectId: 'tasknote-e60f0',
    storageBucket: 'tasknote-e60f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzMDoukJwVUJ9u-FmWY6gHOlM6utVYixg',
    appId: '1:253672631306:ios:d83feed187bfa0bdc583f3',
    messagingSenderId: '253672631306',
    projectId: 'tasknote-e60f0',
    storageBucket: 'tasknote-e60f0.firebasestorage.app',
    iosBundleId: 'com.sks.tasknote',
  );
}
